services:
  postgres:
    image: postgres:15
    container_name: postgres-warehouse
    restart: always
    env_file: .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis-warehouse
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  app:
    build: .
    container_name: ${APP_NAME}
    restart: always
    env_file: .env.dev
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${APP_PORT}:8080"
    networks:
      - backend
  emulator:
    build:
      context: ./robot_emulator
      dockerfile: Dockerfile
    container_name: robot-emulator
    env_file: .env.dev
    depends_on:
      - postgres
      - redis
      - app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      API_URL: http://app:8080

      MODE: live
      ROBOTS_COUNT: ${ROBOTS_COUNT:-4}
      UPDATE_INTERVAL: ${UPDATE_INTERVAL:-8}
      STATUS_INTERVAL: ${STATUS_INTERVAL:-8}
      ROBOT_AUTH_TOKEN: ${ROBOT_AUTH_TOKEN:-}
    networks:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
