services:
  pg:
    image: postgres:15-alpine
    container_name: wh-pg-test
    environment:
      POSTGRES_DB: smart_warehouse_test
      POSTGRES_USER: wh
      POSTGRES_PASSWORD: whpwd
    ports:
      - "54329:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U wh -d smart_warehouse_test"]
      interval: 2s
      timeout: 2s
      retries: 20
