spring:
  application:
    name: warehouse
  datasource:
    # 1) Если задан SPRING_DATASOURCE_URL — используем его.
    # 2) Иначе соберём URL из DB_HOST/DB_PORT (если есть) или дефолтов localhost:5433.
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${POSTGRES_DB:smart_warehouse}?sslmode=disable}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}

    url: jdbc:postgresql://localhost:5433/smart_warehouse
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    lettuce:
      pool:
        enabled: true

  liquibase:
    change-log: classpath:db/changelog/master-changelog-v1.1.yaml
    enabled: true
    clear-checksums: true
server:
  port: ${APP_PORT:8080}

ml:
  api:
    url: http://ai-service:8001

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-exp-seconds: 86400000
    refresh-token-exp-seconds: 1209600

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

app:
  dashboard:
    ttl:
      minute-series-seconds: 4000      # ~66 минут для поминутной серии
      checked-day-days: 3              # ежедневно – хранить 3 дня