spring:
  application:
    name: warehouse
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}

  liquibase:
    change-log: classpath:db/changelog/master-changelog-v1.1.yaml
    enabled: true

server:
  port: ${APP_PORT}

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-exp-seconds: 86400000
    refresh-token-exp-seconds: 1209600

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

warehouse:
  robot:
    recent-scans-key-template: "robot:%s:recent_scans"
    redis-channel: "ws:robot_updates"
    ws-global-topic: "/topic/dashboard"
    ws-robot-topic-prefix: "/topic/dashboard/robot"
    ws-warehouse-topic-prefix: "/topic/dashboard/warehouse"
    ws-global-locations-topic: "/topic/dashboard/locations"
    ws-warehouse-locations-topic-prefix: "/topic/dashboard/warehouse"
    recent-scans-limit: 5
    heartbeat-millis: 5000
    recent-scans-ttl-days: 7
  location:
    heartbeat-millis: 600000
    recent-threshold-minutes: 15
    medium-threshold-minutes: 120
